version: '3.8'

services:
  backend:
    build:
      context: ./infrastructure
      dockerfile: Dockerfile
    container_name: infrastructure
    ports:
      - "3001:3001"
    networks:
      - app-network
    env_file:
      - ./infrastructure/.env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend
    env_file:
      - ./client/.env

networks:
  app-network:
    driver: bridge
