export const FOOTER_DATA = [
    { link: "/register" },
    { link: "/" },
    { link: "/" },
    { link: "/" },
    { link: "/register" },
    { link: "/" },
    { link: "/" },
    { link: "/" },
    { link: "/login" },
    { link: "/" },
    { link: "/" },
    { link: "/" },
    { link: "/zainspotter" },
]